# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  RePlex_config = debug
  RePlexRuntime_config = debug
  RePlexTest_config = debug
endif
ifeq ($(config),release)
  RePlex_config = release
  RePlexRuntime_config = release
  RePlexTest_config = release
endif

PROJECTS := RePlex RePlexRuntime RePlexTest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

RePlex:
ifneq (,$(RePlex_config))
	@echo "==== Building RePlex ($(RePlex_config)) ===="
	@${MAKE} --no-print-directory -C . -f RePlex.make config=$(RePlex_config)
endif

RePlexRuntime: RePlex
ifneq (,$(RePlexRuntime_config))
	@echo "==== Building RePlexRuntime ($(RePlexRuntime_config)) ===="
	@${MAKE} --no-print-directory -C . -f RePlexRuntime.make config=$(RePlexRuntime_config)
endif

RePlexTest:
ifneq (,$(RePlexTest_config))
	@echo "==== Building RePlexTest ($(RePlexTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f RePlexTest.make config=$(RePlexTest_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f RePlex.make clean
	@${MAKE} --no-print-directory -C . -f RePlexRuntime.make clean
	@${MAKE} --no-print-directory -C . -f RePlexTest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   RePlex"
	@echo "   RePlexRuntime"
	@echo "   RePlexTest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"